apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: pm3org-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
        kubernetesUrl: https://46.62.234.169:18443
      vault:
        type: hashicorp
        network: fabric
        address: http://192.168.49.1:8200
        authPath: localpm3org
        secretEngine: secretsv2
        secretPrefix: "data/localpm3org"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: pm3fraktal.se
        externalIp: 46.62.234.169

    storage:
      enabled: False
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false
      nameOverride: pm3org-bevel-storageclass

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: pm3org-admin
      adminPassword: pm3org-adminpw
      subject: "/C=SE/ST=Lulea/L=Lulea/O=Orderer/CN=ca.pm3org-net"
      clusterIpPort: 7054

