apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peer0
  namespace: ombud2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-peernode    
  values:
    global:
      version: 2.5.4
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: fabric
        address: http://192.168.49.1:8200
        authPath: localombud2
        secretEngine: secretsv2
        secretPrefix: "data/localombud2"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: pm3fraktal.se
        externalIp: 46.62.234.169

    storage:
      enabled: False
      peer: 512Mi
      couchdb: 512Mi
      reclaimPolicy: "Delete" 
      volumeBindingMode: Immediate 
      allowedTopologies:
        enabled: false
      nameOverride: storage-peer0

    certs:
      generateCertificates: true
      orgData:
        caAddress: ca.ombud2-net.pm3fraktal.se
        caAdminUser: ombud2-admin
        caAdminPassword: ombud2-adminpw
        orgName: ombud2
        type: peer
        componentSubject: "O=Ombud2,OU=Ombud2,L=Lulea,C=SE"

      users: 
        usersList:
        - {'user': None, 'identity': 'user1', 'attributes': [{'key': 'hf.Revoker', 'value': 'true'}]}

      settings:
        createConfigMaps: True
        refreshCertValue: false
        addPeerValue: false
        removeCertsOnDelete: true
        removeOrdererTlsOnDelete: true

    image:
      couchdb: ghcr.io/hyperledger/bevel-fabric-couchdb
      peer: ghcr.io/hyperledger/bevel-fabric-peer
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: ""

    peer:
      gossipPeerAddress: peer0.ombud2-net.pm3fraktal.se:443
      logLevel: info
      localMspId: ombud2MSP
      tlsStatus: true
      cliEnabled: False
      ordererAddress: orderer1.pm3org-net.pm3fraktal.se:443
      builder: hyperledger/fabric-ccenv
      couchdb:
        username: ombud2-user
        password: ombud2-userpw
      mspConfig:
        organizationalUnitIdentifiers:
        nodeOUs:
          clientOUIdentifier: client
          peerOUIdentifier: peer
          adminOUIdentifier: admin
          ordererOUIdentifier: orderer
      serviceType: ClusterIP 
      loadBalancerType: ""
      ports:
        grpc:
          clusterIpPort: 7051
        events:
          clusterIpPort: 7053
        couchdb:
          clusterIpPort: 5984
        metrics:
          enabled: False
          clusterIpPort: 9443    
      resources:
        limits:
          memory: 1Gi
          cpu: 1
        requests:
          memory: 512M
          cpu: 0.25
      upgrade: False
      healthCheck: 
        retries: 20
        sleepTimeAfterError: 15

