apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: approve-transporter1-pm3-peer0firefly-go1-1
  namespace: transporter1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: approve-transporter1-pm3-peer0firefly-go1-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-chaincode-approve
  values:
    metadata:
      namespace: transporter1-net
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.5.4
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.transporter1-net:7051
      localmspid: transporter1MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.49.1:8200
      authpath: localtransporter1
      adminsecretprefix: secretsv2/data/localtransporter1/users/admin
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      tls: false
    orderer:
      address: orderer1.pm3org-net.pm3fraktal.se:443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.5.4
      name: firefly-go
      version: 1
      sequence: 1
      lang: golang
      commitarguments: ''
      endorsementpolicies:  ''
      initrequired: false
      repository:
        hostname: "github.com"
        git_username: "Fraktal-PM3"
        url: github.com/Fraktal-PM3/firefly.git
        branch: main
        path: smart_contracts/fabric/firefly-go/
      pdc:
        enabled: false
        collectionsconfig:  ""
    channel:
      name: pm3
